<a href="https://colab.research.google.com/github/19PA1A02A7/AI-Lab/blob/master/experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Artificial Intelligence Tools,Techniques and Applications*

# "Experiment No1: Numpy"

# 1) Different ways to create numpy arrays

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[91,92,93]])
print(a)

[[ 1  2  3]
 [91 92 93]]


# 2)Add, remove, modify elements in an array

**Add**:

In [ ]:
 
a = np.array([1,2,3])
b = np.append(a,[80,90,100])
print(b)

[  1   2   3  80  90 100]


**Remove**:

In [ ]:
 
c = np.delete(a,2)
print(c)

[1 2]


**Modify**:

In [ ]:
 
c[c<5]=-1
print(c)

[-1 -1]


# 3) Arithmetic operations on Numpy arrays

In [ ]:
 
import numpy as np
a = ([11,22,33])
b = ([77,88,99])
num_sum = np.add(a,b)
num_diff = np.subtract(a,b)
num_quo = np.divide(a,b)
num_mod = np.mod(a,b)
num_pow = np.power(a,b)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[ 88 110 132]
[-66 -66 -66]
[0.14285714 0.25       0.33333333]
[11 22 33]
[-4237123008362168005                    0  8674848675847231585]


# 4)Slicing and iterating of Numpy arrays

**Slicing**:

In [ ]:
 
import numpy as np
arr = np.array([11,22,33,44,55,66,77,88,99])
print(arr[1:8])

[22 33 44 55 66 77 88]


**Iterating**:

In [ ]:
for x in arr:
 print (x)

11
22
33
44
55
66
77
88
99


# 5)Matrix operations on Numpy arrays

In [ ]:
 
import numpy as np
a = np.array([[11,22],[33,44]])
b = np.array([[55,66],[77,88]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[ 66  88]
 [110 132]]
[[-44 -44]
 [-44 -44]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
